on:
  issues:
    types: [opened, edited]

jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          ISSUEHOST: ${{ secrets.ISSUE }}
        run: node ./script/issue.js
